ast2vec/nbow.py
ast2vec/repo2coocc.py

* remove duplication of code - utilize transformer whenever it's possible
* docs

repo2coocc: refactoring: style, function & variable names, etc

---

ast2vec/id_embedding.py
ast2vec/repo2base.py

Use solution from the standard library.

Replace DictAttr with argparse.Namespace

---

ast2vec/repo2base.py
ast2vec/repo2coocc.py

grpc channels were immortal -> run out of threads
Right now it's fixed.
+ add names to threads

Fix bug with gRPC multithreading

---

ast2vec/model.py
ast2vec/tests/test_model.py
ast2vec/tests/test_repo2nbow.py

Model is pickable:
* __setstate__, __getstate__ + initialization by another model
Tests for Repo2nBOWTransformer: check that transform method works.

Model is pickable, tests for Repo2nBOWTransformer

---

ast2vec/id_embedding.py
ast2vec/tests/test_id_embedding.py

* workaround for bug in tensorflow
* test for SwivelTransformer

Fix SwivelTransformer + test for SwivelTransformer

---

ast2vec/cloning.py
ast2vec/repo2/base.py
ast2vec/repo2/source.py
ast2vec/resolve_symlink.py
ast2vec/tests/test_repo2source.py
ast2vec/tests/test_resolve_symlink.py
ast2vec/tests/test_utils.py

This edits hard to test and it is more for our own convenience.
So I do not cover this changes with tests.

Improve logging and exception catching

---

ast2vec/repo2/base.py
ast2vec/repo2/uast.py
ast2vec/tests/test_repo2base.py

+ minor change in repo2uast: saving response.uast instead of full response.

Add bblfsh errors processing

---

.travis.yml
ast2vec/bblfsh_roles.py
ast2vec/lazy_grpc.py
ast2vec/model2/source2bow.py
ast2vec/repo2/base.py
ast2vec/repo2/coocc.py
ast2vec/tests/__init__.py
ast2vec/tests/test_repo2source.py
ast2vec/tests/test_repo2uast.py
ast2vec/tests/test_source.py
ast2vec/tests/test_token_parser.py
ast2vec/token_parser.py
ast2vec/uast.py
requirements.txt

Reanimate the tests

---

ast2vec/__main__.py
ast2vec/repo2/base.py

The flag is already supported in `repo2base`, but was missing in `__main__.py`.

Add bblfsh_raise_errors flag

---

ast2vec/repo2/base.py
ast2vec/tests/test_repo2base.py

Add time logging

---

ast2vec/__main__.py
ast2vec/uast.py
requirements.txt
setup.py

fix requirements for modelforge
fix uast model dump
fix prune-df flag
related to https://github.com/src-d/ml/issues/112

Minor bugs fixed

---

sourced/ml/engine.py
sourced/ml/repo2/wmhash.py
sourced/ml/uast_struct_to_bag.py

* sourced/ml/uast_struct_to_bag.py - random walk logic
* sourced/ml/repo2/wmhash.py - extractor

Add random walks over UASTs

---

sourced/ml/repo2/wmhash.py
sourced/ml/tests/source/test_example.py
sourced/ml/tests/test_uast_struct_to_bag.py
sourced/ml/uast_struct_to_bag.py

* Fix bug
* `UastSeq2Bag` supports multiple length for seq
* Add tests to check that `.uast_to_bag` works in `UastSeq2Bag` & `Uast2RandomWalk2Bag`

Fix bug in uast2seq + add tests

---

sourced/ml/repo2/base.py

* FieldsSelector
* ParquetSaver
* ParquetLoader
* minor modification to UastExtractor

Several additional transformers:

---

Dockerfile
README.md
doc/how_to_use_ast2vec.ipynb

- Update README
- Update jupyter example notebook
- Update requirements.txt
Related to https://github.com/src-d/ml/issues/120

Edit docker to run jupyter notebook with it

---

sourced/ml/repo2/wmhash.py
sourced/ml/uast_struct_to_bag.py

* propagation of OPTS from base class (`BagsExtractor`) to children classes
* modify TF-IDF formula to utilize `scale` - importance for specific extractor

Add weighting to extractors

---

sourced/ml/__main__.py
sourced/ml/algorithms/token_parser.py
sourced/ml/cmd_entries/__init__.py
sourced/ml/cmd_entries/repos2coocc.py
sourced/ml/models/coocc.py
sourced/ml/tests/test_main.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/basic.py
sourced/ml/transformers/coocc.md
sourced/ml/transformers/coocc.py
sourced/ml/transformers/token_mapper.py
sourced/ml/transformers/transformer.py
sourced/ml/utils/bblfsh_roles.py
sourced/ml/utils/engine.py

For now, I rebase `repos2coocc` on the new structure and make it work.
It is the same PR as https://github.com/src-d/ml/pull/125 in functionality sense.
I create another one to have ability find all that was discussed in the previous PR, for example, `create_spark ` and `create_engine ` refactoring. Can close https://github.com/src-d/ml/pull/125 as soon as this one is merged. 
P.S.: All next PR will be as atomic as possible.

repos2coocc on new structure

---

sourced/ml/algorithms/token_parser.py
sourced/ml/algorithms/uast_ids_to_bag.py
sourced/ml/algorithms/uast_struct_to_bag.py
sourced/ml/extractors/identifiers.py
sourced/ml/extractors/literals.py
sourced/ml/extractors/uast_random_walk.py
sourced/ml/extractors/uast_seq.py
sourced/ml/tests/test_uast_struct_to_bag.py

Here I propose my point of view how uast2bow-type algorithm should look like.
Some points were already discussed, some of them not. 
@EgorBu, this refactoring affects a lot of your code, I try to make it better from my point of view, so feel free not to agree with me. Let's discuss. 
I add comments to lines in this commit to make it clearer what I suggest to change and why.

Uast2all refactoring

---

sourced/ml/cmd_entries/repos2coocc.py
sourced/ml/transformers/basic.py

Now you can do the following:
```python
...
.link(Cacher.maybe(args.persist))
...
```
And before it was not consistent. Check in https://github.com/src-d/ml/pull/149/files#diff-653487ec5c95d3a894f70df54a56a7ac

Cacher `maybe` function refactor

---

sourced/ml/utils/engine.py

Related to all other PRs, so I create a new one.

pep8 check fix

---

sourced/ml/extractors/identifiers.py
sourced/ml/extractors/literals.py
sourced/ml/extractors/uast_random_walk.py
sourced/ml/extractors/uast_seq.py
sourced/ml/utils/engine.py

Fix initialization of transformers:
- add **kwargs where it's missed
-  pass **kwargs to a parent class
Fix passing memory config to engine + make error logs

Fix memory config + initialization of transformers

---

sourced/ml/extractors/uast_random_walk.py
sourced/ml/transformers/basic.py

* Add `explained` functionality to ParquetSaver & FieldSelector
* Fix UastRandomWalkBagExtractor initialization
* Modify UastExtractor - don't return rows without UAST

Minor changes - explained, initialization, filtering

---

CONTRIBUTING.md

Signed-off-by: Konstantin Slavnov konstantin@sourced.tech

Fix Project name CONTRIBUTING.md

---

Dockerfile

Required by https://github.com/andrix/python-snappy

Add missing dependency in Dockerfile

---

requirements.txt
setup.py
sourced/ml/__main__.py
sourced/ml/transformers/basic.py
sourced/ml/transformers/batch_transformers.py
sourced/ml/transformers/transformer.py
sourced/ml/utils/engine.py

Also, need to fix Uast2quant. Will be another PR.

Fix BagBatcher for apollo

---

sourced/ml/transformers/basic.py

It is needed for debug purposes (speed up code execution) mostly.
Signed-off-by: Konstantin Slavnov konstantin@sourced.tech

Add Sampler Transformer

---

sourced/ml/__main__.py
sourced/ml/cmd_entries/args.py
sourced/ml/cmd_entries/repos2bow.py
sourced/ml/cmd_entries/repos2coocc.py
sourced/ml/cmd_entries/repos2df.py
sourced/ml/transformers/bow_writer.py
sourced/ml/utils/engine.py

Prepare for Apollo

---

sourced/ml/__main__.py
sourced/ml/cmd_entries/repos2bow.py

Add add_bow_args()

---

sourced/ml/cmd_entries/args.py
sourced/ml/cmd_entries/repos2bow.py
sourced/ml/cmd_entries/repos2coocc.py
sourced/ml/cmd_entries/repos2df.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/bag_features2termfreq.py
sourced/ml/transformers/basic.py
sourced/ml/transformers/bow_writer.py
sourced/ml/transformers/indexer.py
sourced/ml/transformers/moder.py
sourced/ml/transformers/tfidf.py
sourced/ml/transformers/uast2bag_features.py
sourced/ml/transformers/uast2quant.py
sourced/ml/utils/engine.py

Add "func" extraction mode and fix the document name bug

---

sourced/ml/algorithms/uast_struct_to_bag.py
sourced/ml/transformers/basic.py
sourced/ml/transformers/uast2bag_features.py

Modify features extraction algorithms
Fix ParquetLoader
Modify separators a bit

 Improvements: fixes, better feature extraction

---

requirements.txt
setup.py

Signed-off-by: Waren Long <waren@sourced.tech>

Add pandas to requirements

---

sourced/ml/cmd_entries/repos2bow.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/basic.py
sourced/ml/utils/__init__.py
sourced/ml/utils/engine.py
sourced/ml/utils/spark.py

Make able to use repos2bow with parquet files as input.

Separate spark functionality from engine

---

sourced/ml/__init__.py

Please merge https://github.com/src-d/ml/pull/196 first to include it in a new version.
Also, https://github.com/src-d/ml/pull/195 not critical, but good to have.

Bump version

---

requirements.txt
setup.py

it works well and all Travis tests are passed.
It is update of https://github.com/src-d/ml/pull/199

Change pip version in setup.py

---

sourced/ml/cmd_entries/repos2ids.py
sourced/ml/tests/test_content2ids.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/content2ids.py

Signed-off-by: Waren Long <waren@sourced.tech>

Fix bug in language mapping and improve code readability

---

doc/performance.md

Mostly a revamped version of what was said in this issue: https://github.com/src-d/ml/issues/209

Create file for performance recomendations.

---

sourced/ml/__main__.py
sourced/ml/algorithms/uast_ids_to_bag.py
sourced/ml/algorithms/uast_inttypes_to_nodes.py
sourced/ml/algorithms/uast_struct_to_bag.py
sourced/ml/algorithms/uast_to_bag.py
sourced/ml/extractors/bags_extractor.py
sourced/ml/tests/test_df.py
sourced/ml/tests/test_dump.py
sourced/ml/tests/test_inttypes_to_nodes.py
sourced/ml/tests/test_projector.py
sourced/ml/tests/test_quant.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/basic.py
sourced/ml/utils/engine.py

First part of PR monster https://github.com/src-d/ml/pull/205#discussion_r178817634
- fix pep8 in tests
- improve code line breaks
- add typing
- Remove legacy
I hope all comments from previous PR were addressed

Minor improvements

---

sourced/ml/__main__.py
sourced/ml/algorithms/uast_ids_to_bag.py
sourced/ml/algorithms/uast_inttypes_to_nodes.py
sourced/ml/algorithms/uast_struct_to_bag.py
sourced/ml/algorithms/uast_to_bag.py
sourced/ml/cmd_entries/repos2ids.py
sourced/ml/extractors/bags_extractor.py
sourced/ml/tests/test_df.py
sourced/ml/tests/test_dump.py
sourced/ml/tests/test_inttypes_to_nodes.py
sourced/ml/tests/test_projector.py
sourced/ml/tests/test_quant.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/basic.py
sourced/ml/utils/engine.py

PR is based on https://github.com/src-d/ml/pull/218.
I use `CsvSaver` from it.

Improve Repos2ids

---

sourced/ml/__main__.py
sourced/ml/algorithms/__init__.py
sourced/ml/algorithms/uast_to_role_id_pairs.py
sourced/ml/cmd_entries/__init__.py
sourced/ml/cmd_entries/args.py
sourced/ml/cmd_entries/repos2roles_and_ids.py
sourced/ml/extractors/__init__.py
sourced/ml/extractors/roles_and_ids.py
sourced/ml/tests/test_main.py
sourced/ml/tests/test_uast_to_role_id_pairs.py
sourced/ml/transformers/basic.py
sourced/ml/utils/bblfsh_roles.py

This PR is based on https://github.com/src-d/ml/pull/218
Includes:
- new algorithm
- new extractor
- new cmd entry point

Add code for identifier, role dataset generation

---

sourced/ml/__main__.py
sourced/ml/algorithms/__init__.py
sourced/ml/algorithms/uast_id_distance.py
sourced/ml/algorithms/uast_to_id_sequence.py
sourced/ml/cmd_entries/__init__.py
sourced/ml/cmd_entries/repos2id_sequence.py
sourced/ml/extractors/__init__.py
sourced/ml/extractors/id_sequence.py
sourced/ml/tests/test_main.py
sourced/ml/tests/test_uast_to_id_sequence.py

it is based on https://github.com/src-d/ml/pull/221
Includes:
- new algorithm
- new extractor
- new cmd entry point

Add subprogram for identifier sequence extraction

---

sourced/ml/transformers/coocc.py

The same reason as in https://github.com/src-d/ml/pull/207

Fix condition for identifier nodes

---

README.md

Doc: re-using Apache Spark installation

---

sourced/ml/algorithms/uast_inttypes_to_nodes.py
sourced/ml/algorithms/uast_struct_to_bag.py
sourced/ml/extractors/identifiers.py

Add new default parameters to extractors/algorithms based on hyperoptimization experiments

New default parameters

---

sourced/ml/transformers/basic.py
sourced/ml/utils/engine.py

Filter arguments to a function before the call.

Remove `**kwargs` hack and add proper filtering of arguments before call

---

.travis.yml
sourced/ml/algorithms/token_parser.py
sourced/ml/models/__init__.py
sourced/ml/models/tensorflow.py
sourced/ml/tests/models/test_tensorflow.py

Closes https://github.com/src-d/ml/pull/243

TensorFlowModel

---

.travis.yml

Remove the rest of the apt deps in Travis

---

sourced/ml/__main__.py
sourced/ml/cmd_entries/args.py
sourced/ml/cmd_entries/repos2bow.py
sourced/ml/cmd_entries/repos2coocc.py
sourced/ml/cmd_entries/repos2ids.py
sourced/ml/tests/test_basic_transformers.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/basic.py

It helps a lot with performance issues.
I add this transformer to all other subprograms later.

Add repartition into repo2coocc

---

sourced/ml/tests/test_basic_transformers.py
sourced/ml/transformers/basic.py

Replace DataFrames with RDDs in FieldSelector and ParquetSaver

---

sourced/ml/__main__.py

Just make it more understandable.

Fix help message for pid2vec_postproc subcommand

---

sourced/ml/cmd/preprocess_id2vec.py

Raise an error if matrix contains negative elements

Add co-occurrence matrix values check to id2vec_preproc

---

sourced/ml/algorithms/id_splitter/nn_model.py
sourced/ml/tests/test_id_splitter_nn_model.py

Add functionality to create CNN/RNN models
* CNN builder
* RNN builder
* metrics
* tests for metrics
Should be merged after https://github.com/src-d/ml/pull/255

[id-split] part 2: CNN/RNN models

---

sourced/ml/tests/test_dump.py

All in title, took out the skip unittest and removed unnecessary parts

Dulwich is fixed !

---

sourced/ml/models/df.py

on the trail of https://github.com/src-d/ml/pull/305

remove len(border_keys) in greatest()

---

sourced/ml/cmd/id2role_eval.py

Following after https://github.com/src-d/ml/pull/308
Changes:
1. Delete random comments
1. Evaluate on test dataset for better generalization ability estimation. 🤦‍♂️

Polish id2role_eval code, remove the trash

---

sourced/ml/algorithms/id_splitter/features.py

Import keras in algorithms as needed

---

sourced/ml/models/tensorflow.py
sourced/ml/transformers/moder.py

Fix flake8

---

GLOSSARY.md

• Changed 'reporesent' to represent
Signed-off-by: Akshit Sarin <akshitsarin99@gmail.com>

Fixed a Typo

---

sourced/ml/__init__.py
sourced/ml/__main__.py
sourced/ml/algorithms/uast_ids_to_bag.py
sourced/ml/cmd/args.py
sourced/ml/cmd/repos2bow.py
sourced/ml/extractors/literals.py
sourced/ml/tests/__init__.py
sourced/ml/tests/test_basic_transformers.py
sourced/ml/tests/test_df_util.py
sourced/ml/tests/test_quant_util.py
sourced/ml/transformers/basic.py
sourced/ml/transformers/content2ids.py
sourced/ml/transformers/coocc.py
sourced/ml/transformers/moder.py
sourced/ml/transformers/uast2bag_features.py
sourced/ml/transformers/uast2quant.py
sourced/ml/utils/__init__.py
sourced/ml/utils/engine.py

We should make a new release after the merge.

Delete hiding sourced-engine usage from algorithms

---

requirements.txt
setup.py
sourced/ml/__main__.py
sourced/ml/tests/__init__.py
sourced/ml/tests/test_projector.py

Port to Modelforge 0.8

---

requirements.txt
setup.py
sourced/ml/__init__.py

Bump Modelforge version

---

sourced/ml/algorithms/id_splitter/README.md

* explanation about data (how to download and some stats)
* high-level overview of training pipeline with references to code
* how to use - several commands and help

Add documentation about identifier splitter

---

requirements.txt
setup.py
sourced/ml/cmd/repos2bow.py
sourced/ml/tests/test_engine.py
sourced/ml/transformers/indexer.py
sourced/ml/utils/engine.py

* Update requirements and rename `engine` to `jgit-spark-connector`
* Handle KeyErrors during indexing
* Small fix of for Ignition

Several fixes for topic modeling pipeline

---

setup.py
sourced/ml/__init__.py

Bump the version

---

requirements.txt
setup.py
sourced/ml/__init__.py

Update Modelforge dep

---

sourced/ml/algorithms/token_parser.py
sourced/ml/tests/test_token_parser.py

* metadata for identifier reconstruction
* update logic for splitting
* logic for reconstruction of identifier
* test

Add functionality to reconstruct splitted identifier

---

sourced/ml/__main__.py
sourced/ml/cmd/repos2coocc.py
sourced/ml/cmd/repos2df.py
sourced/ml/cmd/repos2id_distance.py
sourced/ml/cmd/repos2id_sequence.py
sourced/ml/cmd/repos2roles_and_ids.py

Fixed https://github.com/src-d/ml/issues/336

Fix UastRow2Document call when a DataFrame is passed
