ast2vec/model2/source2bow.py
ast2vec/model2/source2df.py
ast2vec/tests/test_source2bow.py

@vmarkovtsev I find several bugs in code.
1. MODEL_TO_CLASS has wrong values in several converters.
2. `source2bow_entry` has no `args.df` because it is `args.docfreq`. You can check it in arg parser.
3. And the last one about the size of the dictionary in `UastModel2BOW`. It was on 1 less than provided and if you provide value less than the number of words, an exception would have been raised.

Fixes topn, MODEL_TO_CLASS, args.docfreq

---

ast2vec/model2/base.py

Because we have in `__main__.py`
```python
process_arg = one_arg_parser(
"-p", "--processes", type=int, default=0,
help="Number of processes to use. 0 means CPU count.")
```

Fix zero num_processes parameter in Model2Base

---

ast2vec/vw_dataset.py

Because it is not allowed to have this character in document name in vowpal wabbit format.

Fix colon in bow record naming

---

ast2vec/source.py

It is not a bug, because we always pass named arguments or kwargs.

Change parameter order to more natural one

---

README.md

Just changed from 'https://github.com/src-d/rol2vec' to 'https://github.com/src-d/role2vec'

fixed typo in link to role2vec (Readme.md)

---

README.md

Changed from 'Doc/how_to_use_ast2vec.ipynb' to 'doc/how_to_use_ast2vec.ipynb'

Fixed link for 'how_to_use_ast2vec'

---

doc/how_to_use_ast2vec.ipynb

Related to https://github.com/src-d/ml/issues/120

Fix setup_logging missing dependency in how_to_use_ast2vec.ipynb

---

sourced/ml/algorithms/__init__.py
sourced/ml/algorithms/token_parser.py
sourced/ml/extractors/identifiers.py
sourced/ml/tests/test_token_parser.py

Correspond to https://github.com/src-d/ml/blob/refactor/documentation/proposals/MLIP-000.md#7-move-nooptokenparser-and-hashedtokenparser-to-parcers-and-join-with-notokenparser

[MLIP-000] Merge NoopTokenParser and NoTokenParser

---

setup.py
sourced/__init__.py

Since we have two python packages in one namespace (`ml` and `engine` in `sourced`) it is good to use package namespace to make them work together.
You can find more info about package namespaces [here](http://setuptools.readthedocs.io/en/latest/setuptools.html#namespace-packages).
One can check that everything works using pure ubuntu (for example using docker `docker run -it ubuntu bash`) and run:
``` bash
apt-get update
apt-get install -y --no-install-suggests --no-install-recommends ca-certificates locales git python3 python3-dev libxml2 libxml2-dev libonig2 make gcc curl
curl https://bootstrap.pypa.io/get-pip.py | python3
mkdir workdir
cd workdir/
git clone https://github.com/zurk/ast2vec.git -b pack_namespace
git clone https://github.com/zurk/engine.git -b feature/pack_namespace
cd …
```

Add package namespace

---

sourced/ml/tests/test_transformer.py
sourced/ml/transformers/transformer.py

the bug was:
if you run explode from the begging of a pipeline, you do not execute the first Transformer.

add tests for Transformer class and bug fix

---

sourced/ml/algorithms/uast_struct_to_bag.py
sourced/ml/tests/test_random_walk.py

Random walk stucks in case there are two same nodes in walk one after another. It should not happen at all.
Also, test added.
Signed-off-by: Konstantin Slavnov konstantin@sourced.tech

Fix random walk algorithm.

---

sourced/ml/cmd_entries/preprocess_id2vec.py
sourced/ml/cmd_entries/run_swivel.py

Avoid import error on systems without `tensorflow`.

Wrap import of tensorflow to avoid import error

---

requirements.txt
setup.py

Updated PR for https://github.com/src-d/ml/pull/186#event-1498671266
I really do not like this messages
```
pkg_resources.DistributionNotFound: The 'pyspark==2.2.0.post0' distribution was not found and is required by sourced-ml
```
:)
Now it should work

Fix pyspark version

---

requirements.txt
setup.py
sourced/ml/__main__.py
sourced/ml/cmd_entries/repos2ids.py

Signed-off-by: Waren Long <waren@sourced.tech>
`pip3 install pandas` is super slow and it could easily be removed saving the CSV file like this:

Remove pandas because to slow to install

---

.travis.yml

The same way as in https://github.com/src-d/minhashcuda
there are 2 stages: testing, using python 3.4,5,6 and deploying. 
`python3 setup.py bdist_wheel` creates `sourced_ml-0.4.4-py3-none-any.whl` file, so there is no need to use `auditwheel` tool. 
Also I change `docker exec -it bblfshd bblfshctl driver install --all` to `docker exec -it bblfshd bblfshctl driver install python bblfsh/python-driver` because we need only one driver for testing and the error `API rate limit exceeded` inside Travis.
```
[0K$ docker exec -it bblfshd bblfshctl driver install --all
Error, GET https://api.github.com/orgs/bblfsh/repos?page=1&per_page=100&type=public: 403 API rate limit exceeded for 35.184.96.71. (But here's the good news: Authenticated requests get a higher rate limit. Check out the …
```

Add deployment via travis

---

requirements.txt
setup.py
sourced/ml/utils/engine.py

Anyway, we should use the same versions of `sourced-engine` jar file and python module. So I add this logic to avoid mistakes. 
for now it is 0.5.3.
One thing, should we add `pip` to requirements?

Add sourced-engine version auto-update

---

sourced/ml/models/df.py

now if you run `python3 -m sourced.ml dump df.asdf` you get
```
{'created_at': datetime.datetime(2018, 3, 16, 15, 7, 15, 490385),
'dependencies': [],
'model': 'docfreq',
'uuid': '5337ac75-ab3d-4dc6-8a72-577da2b646a9',
'version': [1, 0, 0]}
Number of words: 275
Random 10 words: <itertools.islice object at 0x7f6738e8ddb8>
Number of documents: 46
```
`<itertools.islice object at 0x7f6738e8ddb8>` is not what we want. 
I also add frequencies output, because it is important to see them. You will get something like:
```
{'created_at': datetime.datetime(2018, 3, 16, 15, 7, 15, 490385),
'dependencies': [],
'model': 'docfreq',
'uuid': '5337ac75-ab3d-4dc6-8a72-577da2b646a9',
'version': [1, 0, 0]}
Number of words: 275
Random 10 words: {'i.crmessag': 7.0, 'i.descript': 2.0, 'i.servic': 9.0, 'i.class': …
```

Fix and extend df model dump

---

sourced/ml/algorithms/uast_ids_to_bag.py

For code `a = b.c` we have next UAST:
```
||     Module         FILE, MODULE                                
1  ||     Assign         ┣ BINARY, ASSIGNMENT, EXPRESSION            
1  |a|    Name           ┃ ┣ LEFT, IDENTIFIER, EXPRESSION            
1  |c|    Attribute      ┃ ┣ RIGHT, IDENTIFIER, EXPRESSION, QUALIFIED
1  |b|    Name           ┗ ┗ ┗ QUALIFIED, IDENTIFIER, EXPRESSION     
```
And with old XPATH we get only one identifier `a`. Now we are able to get all three.

Improve XPATH for identifier extraction

---

sourced/ml/utils/spark.py

Spark doesn't seem to like the brackets in the path when adding the zipped dependencies

Take out brackets

---

sourced/ml/transformers/basic.py

If an error happens in `self.parse_uast` it should not fail all computation.
Related to https://github.com/bblfsh/client-python/issues/89

Fix processing failure if bblfsh unable to deserialize response

---

sourced/ml/__main__.py
sourced/ml/cmd_entries/__init__.py
sourced/ml/cmd_entries/args.py

Moved ArgumentDefaultsHelpFormatterNoNone form __main__ to sourced/ml/cmd_entries/args.py and put it into sourced/ml/cmd_entries/__init__.py

Move ArgumentDefaultsHelpFormatterNoNone class 

---

sourced/ml/algorithms/__init__.py
sourced/ml/algorithms/uast_ids_to_bag.py
sourced/ml/algorithms/uast_struct_to_bag.py
sourced/ml/extractors/identifiers.py
sourced/ml/extractors/literals.py
sourced/ml/utils/__init__.py
sourced/ml/utils/bblfsh_roles.py

* replace bblfsh.filter with simple traversal algorithm
* add traversal algorithm to utils
* add bblfsh roles

Hot fix for literals & identifier extractors:

---

requirements.txt
setup.py
sourced/ml/cmd_entries/args.py
sourced/ml/cmd_entries/repos2ids.py
sourced/ml/utils/engine.py
sourced/ml/utils/spark.py

First part of split of [old PR](https://github.com/src-d/ml/pull/223/files), moving pause to the spark args parser. It seems more logical, given we will only use in conjunction with spark.
This also takes out pip of imports: since version 10, we need new way to get engine version. Now using `pkg_ressources` to do it

Move pause arg to spark parser, add pause to repos2id

---

sourced/ml/tests/test_engine.py
sourced/ml/utils/engine.py
sourced/ml/utils/spark.py

Simple PR to add a `try`/`except` block in the engine version detection, and default to "0.5.7" if the engine is not detected. This solves a very dumb bug that happens when using Spark in Cluster mode with `ml`, that I describe below. I had not seen it until now because I was replacing this detection with the appropriate `engine` version, e.g. `VERSION = "0.5.7"`, due to a different bug (something to do with `pip` version 9.2). Since with version 10 of `pip` we now use `pkg_ressources` to detect the `engine` version, I updated the detection and the bug popped up.
**Bug description:** 
When using `ml` with Spark in Cluster mode, we zip `ml` and `engine` then add the zip via `addPyFile` to each worker. If this is not done, our tasks fail, given workers do not have `ml` and `engine` …

Fix: Add try/except to VERSION detection

---

sourced/ml/cmd_entries/repos2bow.py
sourced/ml/cmd_entries/repos2id_distance.py
sourced/ml/cmd_entries/repos2id_sequence.py
sourced/ml/cmd_entries/repos2ids.py
sourced/ml/cmd_entries/repos2roles_and_ids.py
sourced/ml/transformers/bow_writer.py

This PR has 3 components:
- **FIX for batches:** I kept having a bug when writing batches of bags, turns out some of the partitions where empty, which caused a bug in modelforge -> to solve this added a condition to skip the batch if it is empty in the loop over the iterator, in `transformers/bow_writer.py`
- **Remove unused caching in `repos2ids`, `repos2id_distance`, `repos2id_sequence` and `repo2roles_and_ids`:** the caching is simply of no use here, since the spark job is a single series of transformation
- **Remove caching in `repos2bow`:** the caching here actually breaks stuff when the data is too massive. I know it speeds up the process, since we don't have to repeat this phase of the pipe twice: ` UastRow2Document -> UastDeserializer -> Uast2BagFeatures`, *however* the amount of …

Caching PR and fix for batches

---

sourced/ml/algorithms/token_parser.py
sourced/ml/tests/test_token_parser.py

- Add small subtokens not only to the next token but also to the previous:
before:
`'sourced.ml.algorithms.uast_ids_to_bag' -> ['sourc', 'algorithm', 'mlalgorithm', 'uast', 'ids', 'bag', 'tobag']`
after: 
`'sourced.ml.algorithms.uast_ids_to_bag' -> ["sourc", "sourcedml", "algorithm", "mlalgorithm", "uast", "ids", "idsto", "bag", "tobag"]`
- Add test cases
- refactor `prev_p[0]` to `ret.prev_p`

Improve token parser

---

sourced/ml/__main__.py

While reviewing recent changes in sourced-ml I mentioned that `--max-distance` parameter type was removed accidentally (here: https://github.com/src-d/ml/pull/240/commits/b142e744ce7482f2a2203bf5938bccb5865bcea2#diff-d05e2f6dc6e4e4be28459a2621694d25L107).
So, I restore justice.
Signed-off-by: konstantin <kslavnov@gmail.com>

Fix --max-distance parameter type

---

sourced/ml/tests/test_engine.py
sourced/ml/utils/engine.py

We raised [this issue](https://github.com/src-d/engine/issues/385) which was addressed in [this PR](https://github.com/src-d/engine/pull/395) which just got merged, this PR just ports the change to the Spark configuration in ml.

Add handling of read errors to spark conf

---

sourced/ml/__main__.py
sourced/ml/cmd/args.py
sourced/ml/cmd/preprocess_id2vec.py
sourced/ml/cmd/projector_entry.py
sourced/ml/cmd/repos2bow.py
sourced/ml/cmd/repos2coocc.py
sourced/ml/cmd/repos2df.py
sourced/ml/tests/test_df_util.py
sourced/ml/tests/test_id2vec.py
sourced/ml/tests/test_id_embedding.py
sourced/ml/utils/docfreq.py

**CONTEXT**
While running apollo on PGA, my job failed after ~36h, out of which 20h were spent creating then writing the docfreq model. The reason for failure seems to be due to Spark instability with ml when processing very large amounts of data (shuffling of ~1TB happened multipl times ...). So I relaunched it, but instead of recalculating the ordered docfreq, I simply edited the code to not waste 20h recreating the already existing ordered docfreq model. I think that this should be integrated to the code, as in my case it halfs processing time, which is rather long - and from what I saw it can be used for both repos2cooc and repos2bow. 
**CHANGES**
- I added the file `utils/docfreq` for the `create_or_load_ordered_df` function used both in repos2cooc and repos2bow. It takes as input …

Add create_or_load_ordered_df function

---

sourced/ml/__main__.py
sourced/ml/cmd/__init__.py
sourced/ml/cmd/args.py
sourced/ml/cmd/merge_df.py
sourced/ml/models/__init__.py
sourced/ml/models/model_converters/base.py
sourced/ml/models/model_converters/merge_df.py
sourced/ml/tests/models/test_tensorflow.py
sourced/ml/tests/test_args.py
sourced/ml/tests/test_main.py
sourced/ml/tests/test_merge_df.py
sourced/ml/tests/test_model2base.py

Since we need to merge the models, as a spark is not reliable enough I add `merge_df` subcommand.
As was discussed I take the old code for Document Frequencies model because it is small enough to be processed by one node. 
I make some minor modifications just to integrate old code to the new codebase and write more tests in `test_merge_df.py`.
The biggest files `model_converters/base.py` and `test_model2base.py` are mostly the same.

Add subcommand to merge Document Frequencies model

---

sourced/ml/__main__.py
sourced/ml/cmd/__init__.py
sourced/ml/cmd/merge_coocc.py
sourced/ml/models/coocc.py
sourced/ml/tests/test_main.py
sourced/ml/tests/test_merge_coocc_entry.py
sourced/ml/transformers/coocc.py

Depends on https://github.com/src-d/ml/pull/252, but they are not tightly coupled.
Since we need to merge the models, as a spark is not reliable enough I add `merge_coocc` subcommand.
As was discussed I use spark to process data because it can be big enough not to be processed by one node. I decided not to add another Transformer because this subcommand is quite different from our `repo2` commands.

Add coocc model merger

---

sourced/ml/cmd/repos2bow.py
sourced/ml/tests/test_basic_transformers.py
sourced/ml/transformers/basic.py

**CONTEXT**
One of the reasons we added the repartionner was to allow the user to choose more freely the number of partitions. In `repos2bow_template`, given the instability of cassandra, we multiply that value by 10 before writing the bags. Problem is by default the value is None, so if not specified this creates a situation where we do:  
```
bags_writer = bags_writer \
.link(Repartitioner.maybe(None * 10, args.shuffle)) \
.link(save_hook())
```
**CHANGES**
Since in the `maybe` method we check for `args.partitions` to be None like in the Cacher, we can simply add a `multiplier` parameter to this method that defaults to 1. I added a test for this, and modified `repos2bow_template` in consequence.

[FIX] Bug in repartionner transformer

---

sourced/ml/__main__.py
sourced/ml/cmd/__init__.py
sourced/ml/cmd/args.py
sourced/ml/cmd/repos2bow.py
sourced/ml/cmd/repos2df.py
sourced/ml/models/df.py
sourced/ml/models/quant.py
sourced/ml/tests/test_df_util.py
sourced/ml/tests/test_indexer.py
sourced/ml/tests/test_main.py
sourced/ml/tests/test_quant_util.py
sourced/ml/transformers/indexer.py
sourced/ml/transformers/uast2quant.py
sourced/ml/utils/quant.py

[Linked PR in apollo](https://github.com/src-d/apollo/pull/61/)
**IDEA**
So since on huge batches this has not proven robust for now, and given the point of failure is during the calculation of TermFrequency right before TFIDF, I think we can run once on all the data to get the DocFreq model as well as a pickle of the index of all documents.
With these available, we can run on subsets of the total without loosing any  - the only thing is not to forget to rename the output bags or they will be overwritten.
**CONTEXT**
Don't know if this works although it should, running it tonight/tomorrow. Would like input if possible.
**CHANGES**
- main: added pickle_index as an optional input or output path. if supplied the pickle will be loaded/saved to the location
- transformers/index: logic of above …

Add option to pickle doc index and stop_pipeline of repo2bow

---

sourced/ml/cmd/repos2bow.py

Typo that pasted under the radar before merge

[FIX] Correct typo in repos2bow_template

---

.flake8
.travis.yml
sourced/ml/algorithms/__init__.py
sourced/ml/algorithms/id_splitter/features.py
sourced/ml/algorithms/uast_id_distance.py
sourced/ml/cmd/__init__.py
sourced/ml/cmd/repos2df.py
sourced/ml/cmd/repos2id_distance.py
sourced/ml/extractors/__init__.py
sourced/ml/extractors/id_sequence.py
sourced/ml/models/__init__.py
sourced/ml/models/model_converters/base.py
sourced/ml/models/model_converters/merge_df.py
sourced/ml/tests/models/test_tensorflow.py
sourced/ml/tests/test_coocc.py
sourced/ml/tests/test_df_util.py
sourced/ml/tests/test_dump.py
sourced/ml/tests/test_id2vec.py
sourced/ml/tests/test_id_splitter_features.py
sourced/ml/tests/test_projector.py
sourced/ml/tests/test_topics.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/basic.py
sourced/ml/transformers/tfidf.py
sourced/ml/transformers/uast2quant.py
sourced/ml/utils/__init__.py
sourced/ml/utils/spark.py

Implementation of #280 
`# flake8: noqa` at the top of the `__init__.py` files to get rid of the warnings about unused imports

Change pep8 to flake8 and fix linter errors

---

sourced/ml/cmd/merge_coocc.py

* Strictly convert coocc matrix to coo_matrix format.
* Fix the wrong index for missing tokens.
* Delete checks. They were moved to `load_and_check` function.

Fix merge-coocc cmd command

---

sourced/ml/tests/test_basic_transformers.py
sourced/ml/tests/test_transformer.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/transformer.py

As was discussed here: https://github.com/src-d/ml/pull/284#discussion_r200116805 we decided to add code that will allow us to write  pipelines like:
```python
Ignition(engine) >> HeadFiles() >> LanguageSelector() >> Execute()
```
This PR contains main changes to allow this. Note, that I also add `<<` for `unlink()` method.
Also, I modify `link()` function to allow multiple likage. Example:
```
t1 = DumpTransformer(1)
t2 = DumpTransformer(2)
t31 = DumpTransformer(31)
t32 = DumpTransformer(32)
t1 >> t2 >> (t31, t32)
t1 >> Explode()
```
It creates and executes a tree:
```
t1 - t2 - t31
\
t32
```
To be able to use `>> Execute()` and `>> Explode()` I create special `LeafTransformer`s that cannot be connected to anything else and marks that it is time to execute pipeline. I think it is a most …

Add __rshift__ __lshift__ shortcuts for link and unlink transformers

---

.travis.yml
sourced/ml/__main__.py
sourced/ml/cmd/args.py
sourced/ml/cmd/repos2bow.py
sourced/ml/models/df.py
sourced/ml/tests/test_df_util.py
sourced/ml/tests/test_dump.py
sourced/ml/tests/test_indexer.py
sourced/ml/tests/test_quant_util.py
sourced/ml/tests/test_tfidf.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/basic.py
sourced/ml/transformers/bow_writer.py
sourced/ml/transformers/indexer.py
sourced/ml/transformers/tfidf.py
sourced/ml/utils/docfreq.py
sourced/ml/utils/quant.py

So, again on this. Thought the previous PR was enough, but there were two shortcoming:
- we still had to run repos2bow subdir by subdir, either manually or through bash loops
- on PGA still got OOM errors
**1st commit:**
I added broadcasting in `TFIDF` and `Indexer`transformers, to speed up process and avoid OOM. I removed `cached_index_path`  in `Indexer`'s `__init__` because it was kind of redundant with the `column2id` param. I also replaced in both transformers the use of the model with dicts, because the broadcasting of whole models is more costly.
**2nd commit:**
Even though we can't hold all extracted features at one or we get OOM errors, we can save on disk all of PGA and then iterate on partitions to run the pipeline - as long as TFIDF is done intelligently. To do so we partition …

Make repos2bow work on PGA

---

sourced/ml/__main__.py
sourced/ml/cmd/__init__.py
sourced/ml/cmd/args.py
sourced/ml/cmd/merge_bow.py
sourced/ml/models/__init__.py
sourced/ml/models/model_converters/base.py
sourced/ml/models/model_converters/merge_bow.py
sourced/ml/models/model_converters/merge_df.py
sourced/ml/tests/test_main.py
sourced/ml/tests/test_merge_bow.py
sourced/ml/tests/test_merge_df.py
sourced/ml/tests/test_model2base.py

We have command for merging `docfreq` models, this implements the same thing for `bow` models. I think it is useful because on large inputs of data we can't collect all of them at once and create small batches of bags due to Spark limitations, however it is cumbersome to move around dozen or hundreds of those, and not compact. I also implemented a function to reduce the output bag by keeping only user selected features (default is all). I did that because it ill probably be useful for users, especially if they are downloading the model but only want specific(s) features, however not sure whether it shouldn't also be a method of the BOW model itself, if yes tell me and I'll change structure. I also removed some unused stuff that we forgot to take out.

Add merge bow function

---

sourced/ml/__main__.py
sourced/ml/cmd/args.py
sourced/ml/cmd/preprocess_repos.py
sourced/ml/cmd/repos2bow.py
sourced/ml/cmd/repos2ids.py
sourced/ml/tests/test_language_selector.py
sourced/ml/tests/test_loader.py
sourced/ml/tests/test_uast_to_id_distance.py
sourced/ml/tests/test_uast_to_id_sequence.py
sourced/ml/tests/test_uast_to_role_id_pairs.py
sourced/ml/transformers/__init__.py
sourced/ml/transformers/basic.py

For some of the commands (`repos2roleids`, `repos2id_distance`) we need to know the language for the file. And as usual, it is a good idea to start them after preprocessing step. So I add several things:
1. add `lang` field to a default set to save in preprocessing step.
2. add `LanguageSelector` step if you start from parquet files in `create_uast_source` function. 
3. Adopt `LanguageSelector` itself to work from parquet files.

Add language processing from parquet files

---

requirements.txt

Related issue: https://github.com/src-d/ml/issues/318
Make 
```
pip3 install -r requirements.txt
pip3 install .
```
works.

Fix requirements for python 3.7

---

setup.py

The description is missing at https://pypi.org/project/sourced-ml/:
This PR adds it, using README.md. See https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi for instructions, the main thing is to make sure to use recent twine and setuptools for upload: `pip install -U twine setuptools`.
---
Also, add `python_requires` to help pip install the right version for the user's Python version.
More info on how this works:
* https://packaging.python.org/guides/dropping-older-python-versions/
* https://hackernoon.com/phasing-out-python-runtimes-gracefully-956f112f33c4

setup.py: Add long_description and python_requires

---

setup.py

Signed-off-by: Nikita Titov <nekit94-08@mail.ru>
This fix prevents the crash during the installation on machines with non-standard locales:
https://github.com/RGF-team/rgf/issues/65
https://github.com/henry0312/pytest-codestyle/pull/34

Open README with utf-8

---

.travis.yml
requirements.txt
setup.py
sourced/ml/algorithms/swivel.py
sourced/ml/cmd/id2role_eval.py
sourced/ml/cmd/merge_coocc.py
sourced/ml/tests/test_merge_bow.py
sourced/ml/tests/test_merge_coocc_entry.py

Signed-off-by: Waren Long <waren@sourced.tech>
This is only a temporary fix for https://github.com/src-d/ml/issues/332 as I'd like to remove pandas df to use python RDD in `id2role-eval`. However I'd need to write the tests for this command, so it's not a quick fix

Move pandas from requirements to extras

---

Dockerfile

Hello,
The use of COPY is preferred over ADD when additional functionalities of ADD are not being used (like spraying the contents of a tar in a folder).
Ref:https://docs.docker.com/engine/articles/dockerfile_best-practices/#add-or-copy
Thanks.

Use COPY instead of ADD in Dockerfile

---

sourced/ml/__init__.py
sourced/ml/models/coocc.py

To make tests in https://github.com/src-d/style-analyzer/pull/619 pass inside docker where we do not have pyspark

Remove pyspark import from the coocc model

---

sourced/ml/algorithms/token_parser.py
sourced/ml/tests/test_token_parser.py

Here's the reason for the feature introduction #403.

Add `attach last upper to the next token` implementation
